IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
WHERE SCHEMA_NAME(schema_id) = 'dbo' AND OBJECT_NAME(object_id) ='QRTZ_TRIGGERS' AND type = 'U')
BEGIN
     CREATE TABLE [dbo].[QRTZ_TRIGGERS] ( 
     [SCHED_NAME]      NVARCHAR(120)        NOT NULL,
     [TRIGGER_NAME]    NVARCHAR(200)        NOT NULL,
     [TRIGGER_GROUP]   NVARCHAR(200)        NOT NULL,
     [JOB_NAME]        NVARCHAR(200)        NOT NULL,
     [JOB_GROUP]       NVARCHAR(200)        NOT NULL,
     [DESCRIPTION]     NVARCHAR(250)        NULL,
     [NEXT_FIRE_TIME]  BIGINT              NULL,
     [PREV_FIRE_TIME]  BIGINT              NULL,
     [PRIORITY]        TINYINT             NULL,
     [TRIGGER_STATE]   NVARCHAR(16)         NOT NULL,
     [TRIGGER_TYPE]    NVARCHAR(8)          NOT NULL,
     [START_TIME]      BIGINT              NOT NULL,
     [END_TIME]        BIGINT              NULL,
     [CALENDAR_NAME]   NVARCHAR(200)        NULL,
     [MISFIRE_INSTR]   TINYINT             NULL,
     [JOB_DATA]        VARBINARY(MAX)      NULL,
     [CREATED_BY]         NVARCHAR(225)        NULL,
	 [CREATED_DT]         DATETIME                 NULL,
	 [MODIFIED_BY]        NVARCHAR(225)        NULL,
	 [MODIFIED_DT]        DATETIME                 NULL
)
END

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK) 
JOIN sys.indexes i ON t.object_id = i.object_id AND i.is_primary_key = 1 WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_TRIGGERS' AND t.type = 'U')
BEGIN
     ALTER TABLE dbo.QRTZ_TRIGGERS ADD CONSTRAINT [PK__QRTZ_TRI__20F4F10178DAFC8C]  PRIMARY KEY CLUSTERED  ([SCHED_NAME] ASC, [TRIGGER_NAME] ASC, [TRIGGER_GROUP] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
END

     
IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_T_J'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_TRIGGERS' AND t.type = 'U')
BEGIN
     CREATE NONCLUSTERED  INDEX [IDX_QRTZ_T_J]  ON [dbo].[QRTZ_TRIGGERS] ([SCHED_NAME] ASC, [JOB_NAME] ASC, [JOB_GROUP] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END


IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_T_JG'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_TRIGGERS' AND t.type = 'U')
BEGIN
     CREATE NONCLUSTERED  INDEX [IDX_QRTZ_T_JG]  ON [dbo].[QRTZ_TRIGGERS] ([SCHED_NAME] ASC, [JOB_GROUP] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END


IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_T_C'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_TRIGGERS' AND t.type = 'U')
BEGIN
     CREATE NONCLUSTERED  INDEX [IDX_QRTZ_T_C]  ON [dbo].[QRTZ_TRIGGERS] ([SCHED_NAME] ASC, [CALENDAR_NAME] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END


IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_T_G'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_TRIGGERS' AND t.type = 'U')
BEGIN
     CREATE NONCLUSTERED  INDEX [IDX_QRTZ_T_G]  ON [dbo].[QRTZ_TRIGGERS] ([SCHED_NAME] ASC, [TRIGGER_GROUP] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END


IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_T_STATE'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_TRIGGERS' AND t.type = 'U')
BEGIN
     CREATE NONCLUSTERED  INDEX [IDX_QRTZ_T_STATE]  ON [dbo].[QRTZ_TRIGGERS] ([SCHED_NAME] ASC, [TRIGGER_STATE] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END


IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_T_N_STATE'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_TRIGGERS' AND t.type = 'U')
BEGIN
     CREATE NONCLUSTERED  INDEX [IDX_QRTZ_T_N_STATE]  ON [dbo].[QRTZ_TRIGGERS] ([SCHED_NAME] ASC, [TRIGGER_NAME] ASC, [TRIGGER_GROUP] ASC, [TRIGGER_STATE] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END


IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_T_N_G_STATE'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_TRIGGERS' AND t.type = 'U')
BEGIN
     CREATE NONCLUSTERED  INDEX [IDX_QRTZ_T_N_G_STATE]  ON [dbo].[QRTZ_TRIGGERS] ([SCHED_NAME] ASC, [TRIGGER_GROUP] ASC, [TRIGGER_STATE] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END


IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_T_NEXT_FIRE_TIME'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_TRIGGERS' AND t.type = 'U')
BEGIN
     CREATE NONCLUSTERED  INDEX [IDX_QRTZ_T_NEXT_FIRE_TIME]  ON [dbo].[QRTZ_TRIGGERS] ([SCHED_NAME] ASC, [NEXT_FIRE_TIME] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END


IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_T_NFT_ST'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_TRIGGERS' AND t.type = 'U')
BEGIN
     CREATE NONCLUSTERED  INDEX [IDX_QRTZ_T_NFT_ST]  ON [dbo].[QRTZ_TRIGGERS] ([SCHED_NAME] ASC, [TRIGGER_STATE] ASC, [NEXT_FIRE_TIME] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END


IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_T_NFT_MISFIRE'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_TRIGGERS' AND t.type = 'U')
BEGIN
     CREATE NONCLUSTERED  INDEX [IDX_QRTZ_T_NFT_MISFIRE]  ON [dbo].[QRTZ_TRIGGERS] ([SCHED_NAME] ASC, [MISFIRE_INSTR] ASC, [NEXT_FIRE_TIME] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END


IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_T_NFT_ST_MISFIRE'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_TRIGGERS' AND t.type = 'U')
BEGIN
     CREATE NONCLUSTERED  INDEX [IDX_QRTZ_T_NFT_ST_MISFIRE]  ON [dbo].[QRTZ_TRIGGERS] ([SCHED_NAME] ASC, [MISFIRE_INSTR] ASC, [NEXT_FIRE_TIME] ASC, [TRIGGER_STATE] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END


IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_T_NFT_ST_MISFIRE_GRP'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_TRIGGERS' AND t.type = 'U')
BEGIN
     CREATE NONCLUSTERED  INDEX [IDX_QRTZ_T_NFT_ST_MISFIRE_GRP]  ON [dbo].[QRTZ_TRIGGERS] ([SCHED_NAME] ASC, [MISFIRE_INSTR] ASC, [NEXT_FIRE_TIME] ASC, [TRIGGER_GROUP] ASC, [TRIGGER_STATE] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END


 
