IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
WHERE SCHEMA_NAME(schema_id) = 'dbo' AND OBJECT_NAME(object_id) ='QRTZ_FIRED_TRIGGERS' AND type = 'U')
BEGIN
	 CREATE TABLE [dbo].[QRTZ_FIRED_TRIGGERS] ( 
	 [SCHED_NAME]         NVARCHAR(120)        NOT NULL,
	 [ENTRY_ID]           NVARCHAR(140)        NOT NULL,
	 [TRIGGER_NAME]       NVARCHAR(200)        NOT NULL,
	 [TRIGGER_GROUP]      NVARCHAR(200)        NOT NULL,
	 [INSTANCE_NAME]      NVARCHAR(200)        NOT NULL,
	 [FIRED_TIME]         BIGINT              NOT NULL,
	 [SCHED_TIME]         BIGINT              NOT NULL,
	 [PRIORITY]           TINYINT             NOT NULL,
	 [STATE]              NVARCHAR(16)         NOT NULL,
	 [JOB_NAME]           NVARCHAR(200)        NULL,
	 [JOB_GROUP]          NVARCHAR(200)        NULL,
	 [IS_NONCONCURRENT]   BIT                 NULL,
	 [REQUESTS_RECOVERY]  BIT                 NULL,
	 [CREATED_BY]         NVARCHAR(225)        NULL,
	 [CREATED_DT]         DATETIME                 NULL,
	 [MODIFIED_BY]        NVARCHAR(225)        NULL,
	 [MODIFIED_DT]        DATETIME                 NULL
)
	 PRINT 'CREATE TABLE dbo.QRTZ_FIRED_TRIGGERS'
END

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK) 
JOIN sys.indexes i ON t.object_id = i.object_id AND i.is_primary_key = 1 WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_FIRED_TRIGGERS' AND t.type = 'U')
BEGIN
	 ALTER TABLE dbo.QRTZ_FIRED_TRIGGERS ADD CONSTRAINT [PK__QRTZ_FIR__7793D06D1D17C5D0]  PRIMARY KEY CLUSTERED  ([SCHED_NAME] ASC, [ENTRY_ID] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	 PRINT 'Created primary key PK__QRTZ_FIR__7793D06D1D17C5D0 on table dbo.QRTZ_FIRED_TRIGGERS'
END

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_FT_TRIG_INST_NAME'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_FIRED_TRIGGERS' AND t.type = 'U')
BEGIN
	 CREATE NONCLUSTERED  INDEX [IDX_QRTZ_FT_TRIG_INST_NAME]  ON [dbo].[QRTZ_FIRED_TRIGGERS] ([SCHED_NAME] ASC, [INSTANCE_NAME] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_FT_INST_JOB_REQ_RCVRY'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_FIRED_TRIGGERS' AND t.type = 'U')
BEGIN
	 CREATE NONCLUSTERED  INDEX [IDX_QRTZ_FT_INST_JOB_REQ_RCVRY]  ON [dbo].[QRTZ_FIRED_TRIGGERS] ([SCHED_NAME] ASC, [INSTANCE_NAME] ASC, [REQUESTS_RECOVERY] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_FT_J_G'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_FIRED_TRIGGERS' AND t.type = 'U')
BEGIN
	 CREATE NONCLUSTERED  INDEX [IDX_QRTZ_FT_J_G]  ON [dbo].[QRTZ_FIRED_TRIGGERS] ([SCHED_NAME] ASC, [JOB_NAME] ASC, [JOB_GROUP] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_FT_JG'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_FIRED_TRIGGERS' AND t.type = 'U')
BEGIN
	 CREATE NONCLUSTERED  INDEX [IDX_QRTZ_FT_JG]  ON [dbo].[QRTZ_FIRED_TRIGGERS] ([SCHED_NAME] ASC, [JOB_GROUP] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_FT_T_G'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_FIRED_TRIGGERS' AND t.type = 'U')
BEGIN
	 CREATE NONCLUSTERED  INDEX [IDX_QRTZ_FT_T_G]  ON [dbo].[QRTZ_FIRED_TRIGGERS] ([SCHED_NAME] ASC, [TRIGGER_NAME] ASC, [TRIGGER_GROUP] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_FT_TG'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_FIRED_TRIGGERS' AND t.type = 'U')
BEGIN
	 CREATE NONCLUSTERED  INDEX [IDX_QRTZ_FT_TG]  ON [dbo].[QRTZ_FIRED_TRIGGERS] ([SCHED_NAME] ASC, [TRIGGER_GROUP] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END
