IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
WHERE SCHEMA_NAME(schema_id) = 'dbo' AND OBJECT_NAME(object_id) ='QRTZ_FAILED_TASKS' AND type = 'U')
BEGIN
CREATE TABLE [dbo].[QRTZ_FAILED_TASKS] (
	[JOB_NAME] 			NVARCHAR(120) NOT NULL,
	[TRIGGER_NAME] 		NVARCHAR(200) NOT NULL,
	[RETRIED] 			INT NOT NULL DEFAULT ((0)),
	[RETRIED_DATE] 		BIGINT NOT NULL DEFAULT ((0)),
	[STATE] 			NVARCHAR(16) NOT NULL DEFAULT ('WAITING'),
	[VERSION] 			INT NOT NULL DEFAULT ((0)),
	[CREATED_BY]         NVARCHAR(225)        NULL,
	 [CREATED_DT]         DATETIME                 NULL,
	 [MODIFIED_BY]        NVARCHAR(225)        NULL,
	 [MODIFIED_DT]        DATETIME                 NULL
)
END

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK) 
JOIN sys.indexes i ON t.object_id = i.object_id AND i.is_primary_key = 1 WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_FAILED_TASKS' AND t.type = 'U')
BEGIN
	 ALTER TABLE dbo.QRTZ_FAILED_TASKS ADD CONSTRAINT [PK_QRTZ_FAILED_TASKS]  PRIMARY KEY CLUSTERED ([JOB_NAME],[TRIGGER_NAME],[STATE],[RETRIED_DATE],[VERSION])
	 PRINT 'Created primary key PK_QRTZ_FAILED_TASKS on table dbo.QRTZ_FAILED_TASKS'
END

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name LIKE 'IDX_QRTZ_FT_JT'
WHERE SCHEMA_NAME(t.schema_id) LIKE 'dbo' AND OBJECT_NAME(t.object_id) LIKE 'QRTZ_FAILED_TASKS' AND t.type = 'U')
BEGIN
	CREATE NONCLUSTERED INDEX IDX_QRTZ_FT_JT
	ON [dbo].[QRTZ_FAILED_TASKS] ([JOB_NAME] ASC, [TRIGGER_NAME] ASC, [STATE] ASC, [VERSION] ASC)
	WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
	PRINT 'Created NONCLUSTERED index IDX_QRTZ_FT_JT on dbo.QRTZ_FAILED_TASKS'
END

IF NOT EXISTS(SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'QRTZ_FAILED_TASKS' 
    AND COLUMN_NAME = 'JOB_GROUP') 
BEGIN
    ALTER TABLE dbo.QRTZ_FAILED_TASKS ADD JOB_GROUP NVARCHAR(255);
END

IF NOT EXISTS(SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'QRTZ_FAILED_TASKS' 
    AND COLUMN_NAME = 'TRIGGER_GROUP') 
BEGIN
    ALTER TABLE dbo.QRTZ_FAILED_TASKS ADD TRIGGER_GROUP NVARCHAR(255);
END