IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
WHERE SCHEMA_NAME(schema_id) = 'dbo' AND OBJECT_NAME(object_id) ='QRTZ_CRON_TRIGGERS' AND type = 'U')
BEGIN
	 CREATE TABLE [dbo].[QRTZ_CRON_TRIGGERS] ( 
	 [SCHED_NAME]       NVARCHAR(120)           NOT NULL,
	 [TRIGGER_NAME]     NVARCHAR(200)           NOT NULL,
	 [TRIGGER_GROUP]    NVARCHAR(200)           NOT NULL,
	 [CRON_EXPRESSION]  NVARCHAR(120)           NOT NULL,
	 [TIME_ZONE_ID]     NVARCHAR(80)            NULL,
	 [CREATED_BY]         NVARCHAR(225)        NULL,
	 [CREATED_DT]         DATETIME                 NULL,
	 [MODIFIED_BY]        NVARCHAR(225)        NULL,
	 [MODIFIED_DT]        DATETIME                 NULL
)
	 PRINT 'CREATE TABLE dbo.QRTZ_CRON_TRIGGERS'
END

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK) 
JOIN sys.indexes i ON t.object_id = i.object_id AND i.is_primary_key = 1 WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_CRON_TRIGGERS' AND t.type = 'U')
BEGIN
	 ALTER TABLE dbo.QRTZ_CRON_TRIGGERS ADD CONSTRAINT [PK__QRTZ_CRO__20F4F10120E024FC]  PRIMARY KEY CLUSTERED  ([SCHED_NAME] ASC, [TRIGGER_NAME] ASC, [TRIGGER_GROUP] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	 PRINT 'Created primary key PK__QRTZ_CRO__20F4F10120E024FC on table dbo.QRTZ_CRON_TRIGGERS'
END
