IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
WHERE SCHEMA_NAME(schema_id) = 'dbo' AND OBJECT_NAME(object_id) ='QRTZ_SUCCESSFUL_EVENTS' AND type = 'U')
BEGIN
     CREATE TABLE [dbo].[QRTZ_SUCCESSFUL_EVENTS] ( 
     [JOB_NAME]      NVARCHAR(120)        NOT NULL,
     [TRIGGER_NAME]  NVARCHAR(200)        NOT NULL,
     [MSG]           NVARCHAR(200)        NOT NULL,
     [CREATED_BY]         NVARCHAR(225)        NULL,
	 [CREATED_DT]         DATETIME                 NULL,
	 [MODIFIED_BY]        NVARCHAR(225)        NULL,
	 [MODIFIED_DT]        DATETIME                 NULL
)
END


IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_SE_JT'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_SUCCESSFUL_EVENTS' AND t.type = 'U')
BEGIN
     CREATE NONCLUSTERED  INDEX [IDX_QRTZ_SE_JT]  ON [dbo].[QRTZ_SUCCESSFUL_EVENTS] ([JOB_NAME] ASC, [TRIGGER_NAME] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END
