IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
WHERE SCHEMA_NAME(schema_id) = 'dbo' AND OBJECT_NAME(object_id) ='QRTZ_SCHEDULER_STATE' AND type = 'U')
BEGIN
     CREATE TABLE [dbo].[QRTZ_SCHEDULER_STATE] ( 
     [SCHED_NAME]         NVARCHAR(120)        NOT NULL,
     [INSTANCE_NAME]      NVARCHAR(200)        NOT NULL,
     [LAST_CHECKIN_TIME]  BIGINT              NOT NULL,
     [CHECKIN_INTERVAL]   BIGINT              NOT NULL,
     [CREATED_BY]         NVARCHAR(225)        NULL,
	 [CREATED_DT]         DATETIME                 NULL,
	 [MODIFIED_BY]        NVARCHAR(225)        NULL,
	 [MODIFIED_DT]        DATETIME                 NULL
)
    
END

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK) 
JOIN sys.indexes i ON t.object_id = i.object_id AND i.is_primary_key = 1 WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_SCHEDULER_STATE' AND t.type = 'U')
BEGIN
     ALTER TABLE dbo.QRTZ_SCHEDULER_STATE ADD CONSTRAINT [PK__QRTZ_SCH__C8C3A19EEFC65793]  PRIMARY KEY CLUSTERED  ([SCHED_NAME] ASC, [INSTANCE_NAME] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
     PRINT 'Created primary key PK__QRTZ_SCH__C8C3A19EEFC65793 on table dbo.QRTZ_SCHEDULER_STATE'
END
