IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
WHERE SCHEMA_NAME(schema_id) = 'dbo' AND OBJECT_NAME(object_id) ='QRTZ_CALENDARS' AND type = 'U')
BEGIN
	 CREATE TABLE [dbo].[QRTZ_CALENDARS] ( 
	 [SCHED_NAME]     NVARCHAR(120)             NOT NULL,
	 [CALENDAR_NAME]  NVARCHAR(200)             NOT NULL,
	 [CALENDAR]       VARBINARY(MAX)           NOT NULL,
	 [CREATED_BY]         NVARCHAR(225)        NULL,
	 [CREATED_DT]         DATETIME                 NULL,
	 [MODIFIED_BY]        NVARCHAR(225)        NULL,
	 [MODIFIED_DT]        DATETIME                 NULL
)
	 PRINT 'CREATE TABLE dbo.QRTZ_CALENDARS'
END

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK) 
JOIN sys.indexes i ON t.object_id = i.object_id AND i.is_primary_key = 1 WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_CALENDARS' AND t.type = 'U')
BEGIN
	 ALTER TABLE dbo.QRTZ_CALENDARS ADD CONSTRAINT [PK__QRTZ_CAL__DEBD34E0381E1531]  PRIMARY KEY CLUSTERED  ([SCHED_NAME] ASC, [CALENDAR_NAME] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	 PRINT 'Created primary key PK__QRTZ_CAL__DEBD34E0381E1531 on table dbo.QRTZ_CALENDARS'
END
