IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
WHERE SCHEMA_NAME(schema_id) = 'dbo' AND OBJECT_NAME(object_id) ='QRTZ_JOB_DETAILS' AND type = 'U')
BEGIN
	 CREATE TABLE [dbo].[QRTZ_JOB_DETAILS] ( 
	 [SCHED_NAME]         NVARCHAR(120)        NOT NULL,
	 [JOB_NAME]           NVARCHAR(200)        NOT NULL,
	 [JOB_GROUP]          NVARCHAR(200)        NOT NULL,
	 [DESCRIPTION]        NVARCHAR(250)        NULL,
	 [JOB_CLASS_NAME]     NVARCHAR(250)        NOT NULL,
	 [IS_DURABLE]         BIT                  NOT NULL,
	 [IS_NONCONCURRENT]   BIT                  NOT NULL,
	 [IS_UPDATE_DATA]     BIT                  NOT NULL,
	 [REQUESTS_RECOVERY]  BIT                  NOT NULL,
	 [JOB_DATA]           VARBINARY(MAX)       NULL,
	 [CREATED_BY]         NVARCHAR(225)        NULL,
	 [CREATED_DT]         DATETIME                 NULL,
	 [MODIFIED_BY]        NVARCHAR(225)        NULL,
	 [MODIFIED_DT]        DATETIME                 NULL
)
	 PRINT 'CREATE TABLE dbo.QRTZ_JOB_DETAILS'
END

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK) 
JOIN sys.indexes i ON t.object_id = i.object_id AND i.is_primary_key = 1 WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_JOB_DETAILS' AND t.type = 'U')
BEGIN
	 ALTER TABLE dbo.QRTZ_JOB_DETAILS ADD CONSTRAINT [PK__QRTZ_JOB__E0CAAB8A79739225]  PRIMARY KEY CLUSTERED  ([SCHED_NAME] ASC, [JOB_NAME] ASC, [JOB_GROUP] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	 PRINT 'Created primary key PK__QRTZ_JOB__E0CAAB8A79739225 on table dbo.QRTZ_JOB_DETAILS'
END
	 
IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_J_REQ_RECOVERY'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_JOB_DETAILS' AND t.type = 'U')
BEGIN
	 CREATE NONCLUSTERED  INDEX [IDX_QRTZ_J_REQ_RECOVERY]  ON [dbo].[QRTZ_JOB_DETAILS] ([SCHED_NAME] ASC, [REQUESTS_RECOVERY] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END

IF NOT EXISTS(SELECT TOP 1 1 FROM sys.tables t WITH(NOLOCK)
JOIN sys.indexes i ON t.object_id = i.object_id AND i.name = 'IDX_QRTZ_J_GRP'
WHERE SCHEMA_NAME(t.schema_id) = 'dbo' AND OBJECT_NAME(t.object_id) ='QRTZ_JOB_DETAILS' AND t.type = 'U')
BEGIN
	 CREATE NONCLUSTERED  INDEX [IDX_QRTZ_J_GRP]  ON [dbo].[QRTZ_JOB_DETAILS] ([SCHED_NAME] ASC, [JOB_GROUP] ASC)WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION= NONE, ONLINE=ON, MAXDOP=0,FILLFACTOR = 90) ON [PRIMARY]
END